// <auto-generated />
using System;
using EnerjiTahmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnerjiTahmin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnerjiTahmin.Models.CityTempView", b =>
                {
                    b.Property<double>("AvgTemp")
                        .HasColumnType("double");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("vw_cityaveragetemperature", (string)null);
                });

            modelBuilder.Entity("EnerjiTahmin.Models.DailySummaryView", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalConsumption")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable((string)null);

                    b.ToView("vw_dailyconsumptionsummary", (string)null);
                });

            modelBuilder.Entity("EnerjiTahmin.Models.HighConsumptionView", b =>
                {
                    b.Property<int>("ConsumptionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Lag_24h")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MWh_Value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.ToTable((string)null);

                    b.ToView("vw_highconsumptionhours", (string)null);
                });

            modelBuilder.Entity("EnerjiTahmin.Models.IslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("IslemLoglari");
                });

            modelBuilder.Entity("EnerjiTahmin.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FullName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EnerjiTahmin.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("EnerjiTahmin.Models.TuketimVerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsumptionID");

                    b.Property<decimal>("Lag24")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Lag_24h");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time(6)")
                        .HasColumnName("Time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date");

                    b.Property<double>("TuketimMiktari")
                        .HasColumnType("double")
                        .HasColumnName("MWh_Value");

                    b.HasKey("Id");

                    b.ToTable("electricityconsumptions");
                });

            modelBuilder.Entity("EnerjiTahmin.Models.UserDetailView", b =>
                {
                    b.Property<string>("MaskedEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaskedName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaskedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_userdetails", (string)null);
                });

            modelBuilder.Entity("EnerjiTahmin.Models.Suggestion", b =>
                {
                    b.HasOne("EnerjiTahmin.Models.Kullanici", "GonderenKisi")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GonderenKisi");
                });
#pragma warning restore 612, 618
        }
    }
}
